<Project>
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <LangVersion>latest</LangVersion>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" PrivateAssets="all" />
    <PackageReference Include="Krafs.Rimworld.Ref" PrivateAssets="all" Condition="'$(RimWorldManagedDir)' == ''" />
    <PackageReference Include="Lib.Harmony" ExcludeAssets="runtime" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup Condition="'$(RimWorldManagedDir)' != ''">
    <Reference Include="Assembly-CSharp;UnityEngine.CoreModule;UnityEngine.IMGUIModule">
      <HintPath>$(RimWorldManagedDir)/%(Identity).dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>
